== まとめ

本報告書では、Cordova を利用するハイブリッドアプリに作り込まれうる脆弱性について、アプリの構成要素ごとに考察した。

3章と4章では、OS や WebView が抱える脆弱性が Cordova アプリに及ぼす影響について検討した。端末の OS が古く WebView がアップデートされていない場合には、Crosswalk など第三者が提供する WebView を使うことで、OS が提供する WebView の脆弱性をアプリ側で対策することが可能であるが、プラグインの互換性などの面で課題もある。恒久的な対策としては、OS および WebView の定期的なバージョンアップが求められる。

5章と6章では、Cordova 本体や、Cordova プラグインが抱える脆弱性の傾向について検討した。Cordova のコードベースは規模が大きく、Cordova プラグインの数が多い一方で、これらに対する脆弱性の報告件数は少ない。しかし、本調査を行う過程で Cordova や Cordovaプラグインの脆弱性を新たに発見したように、今後ハイブリッドアプリへの注目が高まれば、より多くの脆弱性が報告されるのは時間の問題であると思われる。ハイブリッドアプリの開発者は、将来これらのコンポーネントに脆弱性が報告された場合に備え、Cordova 本体やアプリで利用するプラグインを定期的にアップデートできる開発体制を確立しておくべきである。また、Cordova プラグインを開発する際は、JavaScript インジェクションをはじめとする脆弱性を組み込まないように注意する必要がある。

7章では、Cordova アプリの JavaScript コードに作り込みうる脆弱性について検討した。脆弱性は HTML5 の機能や Cordova プラグインの誤用によって作り込まれるが、最新のウェブブラウザ実装に対応した HTML5 のセキュアコーディング手法や Cordova プラグインの安全な使い方に関するノウハウは体系的にまとめられてはおらず、開発者を啓発するためのドキュメントの整備が望まれる。
組み込まれる可能性の高い脆弱性の1つとして DOM Based XSS が挙げられるが、DOM Based XSS は開発者によるセキュアコーディグのみで根絶することは困難であり、XSS の対策を行いやすいフレームワークの導入や、CSP の併用等により、多層防御でリスクを軽減することが望ましい。

8章では、Cordova アプリのネイティブコードを開発する際に開発者が作り込む脆弱性について検討した。脆弱性を作り込まないためには、プラットフォームごとのセキュアコーディングの知識を習得し実践することが不可欠である。Android プラットフォームにおけるセキュアコーディングについては、JSSEC が公開する「Androidアプリのセキュア設計・セキュアコーディングガイド」が良い学習教材となる。iOS においては、個々の API の誤用と作り込まれる脆弱性について体系的にまとめたドキュメントは残念ながら存在しない。

9章では、サーバとのネットワーク通信に関する脆弱性について検討した。Cordova アプリでは、ネットワークから取得した HTML や JavaScript などのリソースからブリッジを利用できることから、中間者攻撃が行われた場合の影響が大きい。そのため、HTTPS 通信により信頼できるサーバからリソースを取得することが重要である。最近の WebView には、HSTS や Mixed Content をはじめとする HTTPS を安全に利用するための機能が搭載されていることから、これらを活用し、意図せず HTTP で通信するリスクを軽減することも望ましい。

10章では、サーバ側の脆弱性について検討した。Cordova アプリが悪質な広告を開いた場合、広告を介してブリッジを不正操作される可能性が考えられる。現状の Cordova では、不正な広告にブリッジを利用させないようにする仕組みは無いため、信頼できる広告のみを表示するよう対処するしかない。

11章では、Google Play から実際に取得したハイブリッドアプリに対して静的解析を行い、その実態を浮き彫りにした。この解析結果から、プラグインを誤用しているアプリや、HTTP 経由でリソースを取得するアプリが存在することが明らかになった。

以上のように、Cordova を利用するアプリでは、ネイティブアプリで指摘されてきた従来の脆弱性に加え、Webアプリの脆弱性や、Cordova 固有の脆弱性等、様々な脆弱性の影響を受ける可能性がある。

アプリ開発者自身がセキュアコーディングを行うことで安全なアプリを開発するとともに、Cordova 自体がより安全なアプリを開発できるプラットフォームとして発展することが望まれる。

例えば、Firefox OS や Chrome OS では、アプリの開発者に対して CSP の適用を必須化することにより、DOM Based XSS の低減を実現している。footnote:[https://developer.mozilla.org/en-US/Apps/Build/Building_apps_for_Firefox_OS/CSP] footnote:[https://developer.chrome.com/apps/contentSecurityPolicy]
また、Firefox OS では、HTML や JavaScript のリソースをネットワークから取得する際に、接続先のドメインを制限することに加え、HTTPS 接続と HPKP による証明書ピンニングを必須化することにより、中間者攻撃のリスクを軽減している。footnote:[https://bugzilla.mozilla.org/show_bug.cgi?id=1016421#c0]
このような仕組みが Cordova に導入され、より安全なアプリ開発が可能になることが期待される。

== 今後の調査課題

今後の調査課題を以下に挙げる。

.WKWebViewの調査

iOS版の Cordovaは、将来的に UIWebView から WKWebView に移行される予定である。footnote:[https://issues.apache.org/jira/browse/CB-7991] WKWebView には http://devstreaming.apple.com/videos/wwdc/2014/206xxdiurnffagr/206/206_introducing_the_modern_webkit_api.pdf[Script Messages] をはじめとする新たな機能が搭載されており、それらに対する安全性の検証が必要となる。また、iOS7 までの UIWebView では、file スキームで動作する HTML に XSS が存在する場合、アプリのサンドボックスのリソースを盗まれる恐れがあったことから、WKWebView において file スキームのHTMLが持つ権限やその指定方法についても調査が求められる。

.iOS におけるセキュアコーディングに関するノウハウ

iOS プラットフォームにおける API の誤用と脆弱性についてまとめたガイドは存在しないが、NSXMLParser などは、XMLの外部エンティティ参照を無効化 (shouldResolveExternalEntities に NO を指定) しても無効化されないなど、 https://developer.apple.com/library/ios/documentation/Cocoa/Reference/Foundation/Classes/NSXMLParser_Class/index.html[iOS Developer Library] の情報だけでは、脆弱性を作り込んでしまう可能性がある。iOSにおける正しい API の利用方法の調査と情報発信が望まれる。

.Cordova アプリで安全に広告を開くための仕組みの検討

Cordova では、ホワイトリストで許可したオリジンに対してはブリッジの使用も自動的に許可されてしまうため、ブリッジの利用のみを無効化するという設定はできない。今後、Cordova を利用したアプリが悪質な広告の標的になる可能性も考えられるため、広告の表示は許可しつつも、ブリッジの不正利用を防ぐ仕組みの検討が求められる。

.HTML5 セキュアコーディングガイドの継続的な更新

X.X節では、HTML Imports の不正利用により XSS が発生する可能性について触れた。こうした点について記載されているセキュアコーディングガイドは残念ながら見当たらない。近年のブラウザには、JavaScript で暗号処理を行うことを目的として http://www.w3.org/TR/WebCryptoAPI/[Web Cryptography API] が実装されているが、APIの安全な使い方footnote:[たとえば、暗号化鍵の生成には Math.random() ではなく、暗号学的擬似乱数を取得するCrypto.getRandomValues()関数を使用するなど]を解説したガイドは存在しない。昨今のブラウザの実装を元に、セキュアコーディングガイドを継続的に更新していく仕組み作りが必要である。

.Cordovaプラグインの安全な作り方、使い方に関するノウハウの蓄積

本報告書では、Plugin Registry の上位20位までのプラグインを対象に脆弱性の調査を行ったが、その他のプラグインについても脆弱性の調査を行い、プラグイン自体の脆弱性やアプリによるプラグインの誤用によって作り込まれる脆弱性とその対策に関する情報を蓄積し、安全なアプリ開発のためのガイドを管理する必要がある。
